### ISSUE TITLE
Documentation link on deployed site is out-of-date

### ISSUE THREAD

**Issue by ldct** [plasma-group/website#2]
It links to https://plasma-docs.readthedocs.io/en/latest/ instead of https://plasma-core.readthedocs.io/en/latest/

**Comment by smartcontracts** [comment]
Ty ty! Thanks for the report. We're actually moving everything over to https://docs.plasma.group and related sub-projects (e.g. https://docs.plasma.group/projects/core/en/latest/). Will update these links in a sec.

**Comment by smartcontracts** [comment]
Updated! :+1:
